import type { FormTemplate } from '@/types/form'

export const sestina: FormTemplate = {
  id: 'sestina',
  name: 'Sestina',
  description:
    "39 lines: six 6-line stanzas that all end on the same six words, rotating each stanza by the standard pattern (last, first, second-to-last, second, fourth, third), plus a closing 3-line envoi that uses all six words again — one each at the line's end and one embedded earlier in the line.",
  example: [
    'I still remember the shape of that house',
    'how morning came in through a single light',
    'and settled, warm, along your open hands',
    'before the sky gave way to steady rain',
    'You always left a lamp beside the door',
    'as if the dark might learn to say your name',
    '',
    'I never learned to call it by its name',
    'this quiet ache for one small, distant house',
    'where every hour arrived through the same door',
    'and evening softened into gentler light',
    'I think of it whenever there is rain',
    'the way it used to gather in your hands',
    '',
    'The years have changed the shape of these hands',
    'but not the way I still recall your name',
    "or how we'd stand and listen to the rain",
    'as if the weather understood the house',
    'and dimmed itself to match the fading light',
    'before it slipped in underneath the door',
    '',
    'I keep returning to that narrow door',
    'the one I opened with uncertain hands',
    "not knowing yet how far I'd walk from light",
    'or how much distance fits inside a name',
    "Some nights I dream I'm standing in the house",
    'and waking feels as sudden as the rain',
    '',
    "It's strange what stays after the last, long rain",
    'a certain angle, worn into the door',
    'a certain quiet, settled in the house',
    "a certain warmth I still can't quite call hands",
    'though I keep trying, keep repeating name',
    'as if it were a way of holding light',
    '',
    'There is a version of me made of light',
    'who never learned to leave before the rain',
    "who still remembers everybody's name",
    "who's standing, always, just behind that door",
    'with all the world still gathered in his hands',
    "unwilling, still, to walk out of that house",
    '',
    'Come find me at the door, still chasing light',
    'with empty hands, still waiting for the rain',
    'still calling, from the house, your oldest name',
  ].join('\n'),
  lineRules: [],
  stanzaLineCounts: [6, 6, 6, 6, 6, 6, 3],
  isSestina: true,
}
